import { Dimensions, Platform, StyleSheet } from "react-native";
import { Fonts } from "../../constants";

const { width } = Dimensions.get("window");

export const useNotesScreenStyle = () => {
    const styles = StyleSheet.create({
        safeArea: {
            flex: 1,
            backgroundColor: "#F9FAFB",
        },
        header: {
            paddingHorizontal: 16,
            paddingVertical: 16,
            backgroundColor: "#FFFFFF",
            borderBottomWidth: 1,
            borderBottomColor: "#E5E7EB",
            ...Platform.select({
                ios: {
                    shadowColor: "#000",
                    shadowOffset: { width: 0, height: 2 },
                    shadowOpacity: 0.1,
                    shadowRadius: 4,
                },
                android: {
                    elevation: 4,
                },
            }),
        },
        headerTitleContainer: {
            alignItems: "center",
        },
        headerTitle: {
            fontSize: 28,
            fontWeight: "700",
            color: "#1F2937",
            fontFamily: Fonts.heading.family,
            marginBottom: 4,
        },
        headerSubtitle: {
            fontSize: 15,
            color: "#6B7280",
            fontFamily: Fonts.body.family,
            opacity: 0.8,
        },
        searchContainer: {
            paddingHorizontal: 16,
            paddingVertical: 12,
            backgroundColor: "#FFFFFF",
            borderBottomWidth: 1,
            borderBottomColor: "#E5E7EB",
        },
        searchBar: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: "#F3F4F6",
            borderRadius: 12,
            paddingHorizontal: 16,
            paddingVertical: 10,
            borderWidth: 1,
            borderColor: "#E5E7EB",
        },
        searchInput: {
            flex: 1,
            marginLeft: 12,
            fontSize: 16,
            color: "#1F2937",
            fontFamily: Fonts.body.family,
        },
        noteCard: {
            backgroundColor: "#FFFFFF",
            borderRadius: 16,
            marginVertical: 8,
            marginHorizontal: 16,
            ...Platform.select({
                ios: {
                    shadowColor: "#000",
                    shadowOffset: { width: 0, height: 2 },
                    shadowOpacity: 0.1,
                    shadowRadius: 8,
                },
                android: {
                    elevation: 3,
                },
            }),
            borderWidth: 1,
            borderColor: "#F3F4F6",
        },
        noteHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "flex-start",
            paddingHorizontal: 16,
            paddingTop: 16,
            paddingBottom: 12,
            borderBottomWidth: 1,
            borderBottomColor: "#F3F4F6",
        },
        authorInfo: {
            flexDirection: "row",
            alignItems: "center",
            flex: 1,
        },
        authorAvatar: {
            width: 40,
            height: 40,
            borderRadius: 20,
            justifyContent: "center",
            alignItems: "center",
            marginRight: 12,
            ...Platform.select({
                ios: {
                    shadowColor: "#000",
                    shadowOffset: { width: 0, height: 1 },
                    shadowOpacity: 0.1,
                    shadowRadius: 2,
                },
                android: {
                    elevation: 2,
                },
            }),
        },
        authorInitials: {
            color: "#FFFFFF",
            fontSize: 14,
            fontWeight: "600",
            fontFamily: Fonts.body.family,
        },
        authorDetails: {
            flex: 1,
        },
        authorName: {
            fontSize: 16,
            fontWeight: "600",
            color: "#1F2937",
            fontFamily: Fonts.body.family,
        },
        noteDate: {
            fontSize: 13,
            color: "#9CA3AF",
            marginTop: 2,
            fontFamily: Fonts.body.family,
        },
        noteActions: {
            flexDirection: "row",
            alignItems: "center",
            gap: 8,
        },
        importantBadge: {
            width: 28,
            height: 28,
            borderRadius: 14,
            backgroundColor: "#FEF3C7",
            justifyContent: "center",
            alignItems: "center",
            borderWidth: 1,
            borderColor: "#FCD34D",
        },
        actionButtons: {
            flexDirection: "row",
            gap: 8,
        },
        editButton: {
            width: 34,
            height: 34,
            borderRadius: 17,
            backgroundColor: "#EBF5FF",
            justifyContent: "center",
            alignItems: "center",
            borderWidth: 1,
            borderColor: "#BFDBFE",
        },
        deleteButton: {
            width: 34,
            height: 34,
            borderRadius: 17,
            backgroundColor: "#FEE2E2",
            justifyContent: "center",
            alignItems: "center",
            borderWidth: 1,
            borderColor: "#FECACA",
        },
        noteContentContainer: {
            paddingHorizontal: 16,
            paddingVertical: 16,
        },
        noteContent: {
            fontSize: 16,
            lineHeight: 24,
            color: "#374151",
            fontFamily: Fonts.body.family,
            textAlign: "left",
        },
        // États vides et loading
        loadingContainer: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            padding: 32,
        },
        loadingText: {
            fontSize: 16,
            color: "#6B7280",
            marginTop: 16,
            fontFamily: Fonts.body.family,
        },
        errorContainer: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            padding: 32,
        },
        errorEmoji: {
            fontSize: 48,
            marginBottom: 16,
        },
        errorTitle: {
            fontSize: 20,
            fontWeight: "600",
            color: "#EF4444",
            marginBottom: 8,
            fontFamily: Fonts.heading.family,
        },
        errorText: {
            fontSize: 16,
            color: "#6B7280",
            textAlign: "center",
            marginBottom: 24,
            fontFamily: Fonts.body.family,
        },
        retryButton: {
            backgroundColor: "#7ED957",
            paddingHorizontal: 24,
            paddingVertical: 12,
            borderRadius: 12,
        },
        retryButtonText: {
            color: "#FFFFFF",
            fontSize: 16,
            fontWeight: "600",
            fontFamily: Fonts.body.family,
        },
        emptyState: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            padding: 32,
        },
        emptyEmoji: {
            fontSize: 64,
            marginBottom: 24,
        },
        emptyTitle: {
            fontSize: 24,
            fontWeight: "700",
            color: "#1F2937",
            marginBottom: 8,
            fontFamily: Fonts.heading.family,
        },
        emptySubtitle: {
            fontSize: 18,
            fontWeight: "500",
            color: "#4B5563",
            marginBottom: 16,
            fontFamily: Fonts.body.family,
        },
        emptyDescription: {
            fontSize: 16,
            color: "#6B7280",
            textAlign: "center",
            marginBottom: 32,
            fontFamily: Fonts.body.family,
            lineHeight: 24,
        },
        emptyButton: {
            backgroundColor: "#7ED957",
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: 32,
            paddingVertical: 16,
            borderRadius: 16,
            ...Platform.select({
                ios: {
                    shadowColor: "#000",
                    shadowOffset: { width: 0, height: 4 },
                    shadowOpacity: 0.15,
                    shadowRadius: 8,
                },
                android: {
                    elevation: 6,
                },
            }),
        },
        emptyButtonText: {
            color: "#FFFFFF",
            fontSize: 16,
            fontWeight: "600",
            marginLeft: 12,
            fontFamily: Fonts.body.family,
        },
        // Bouton flottant
        floatingAddButton: {
            position: "absolute",
            bottom: 24,
            right: 24,
            width: 64,
            height: 64,
            borderRadius: 32,
            backgroundColor: "#7ED957",
            justifyContent: "center",
            alignItems: "center",
            ...Platform.select({
                ios: {
                    shadowColor: "#000",
                    shadowOffset: { width: 0, height: 4 },
                    shadowOpacity: 0.3,
                    shadowRadius: 8,
                },
                android: {
                    elevation: 8,
                },
            }),
        },
        // Modal styles
        modalOverlay: {
            flex: 1,
            backgroundColor: "rgba(0, 0, 0, 0.5)",
            justifyContent: "flex-end",
        },
        modalContainer: {
            backgroundColor: "#FFFFFF",
            borderTopLeftRadius: 24,
            borderTopRightRadius: 24,
            paddingTop: 24,
            paddingBottom: Platform.OS === "ios" ? 44 : 24,
            maxHeight: "80%",
            ...Platform.select({
                ios: {
                    shadowColor: "#000",
                    shadowOffset: { width: 0, height: -4 },
                    shadowOpacity: 0.1,
                    shadowRadius: 12,
                },
                android: {
                    elevation: 12,
                },
            }),
        },
        modalHeader: {
            paddingHorizontal: 24,
            paddingBottom: 16,
            borderBottomWidth: 1,
            borderBottomColor: "#E5E7EB",
            alignItems: "center",
        },
        modalTitle: {
            fontSize: 20,
            fontWeight: "700",
            color: "#1F2937",
            fontFamily: Fonts.heading.family,
        },
        modalContent: {
            paddingHorizontal: 24,
            paddingVertical: 16,
        },
        noteInput: {
            borderWidth: 1,
            borderColor: "#D1D5DB",
            borderRadius: 12,
            padding: 16,
            fontSize: 16,
            fontFamily: Fonts.body.family,
            color: "#1F2937",
            textAlignVertical: "top",
            minHeight: 120,
            maxHeight: 200,
        },
        importantToggle: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            marginTop: 16,
            padding: 16,
            backgroundColor: "#F9FAFB",
            borderRadius: 12,
            borderWidth: 1,
            borderColor: "#E5E7EB",
        },
        modalActions: {
            flexDirection: "row",
            gap: 12,
            paddingHorizontal: 24,
            paddingTop: 16,
        },
        cancelButton: {
            flex: 1,
            paddingVertical: 16,
            borderRadius: 12,
            backgroundColor: "#F3F4F6",
            alignItems: "center",
        },
        cancelButtonText: {
            fontSize: 16,
            fontWeight: "600",
            color: "#6B7280",
            fontFamily: Fonts.body.family,
        },
        saveButtonText: {
            fontSize: 16,
            fontWeight: "600",
            color: "#FFFFFF",
            fontFamily: Fonts.body.family,
        },
        importantText: {
            fontSize: 16,
            fontWeight: "500",
            color: "#6B7280",
            fontFamily: Fonts.body.family,
        },
        importantTextActive: {
            fontSize: 16,
            fontWeight: "500",
            color: "#F59E0B",
            fontFamily: Fonts.body.family,
        },
        saveButton: {
            flex: 1,
            backgroundColor: "#7ED957",
            paddingVertical: 16,
            borderRadius: 12,
            alignItems: "center",
        },
        saveButtonDisabled: {
            flex: 1,
            backgroundColor: "#9CA3AF",
            paddingVertical: 16,
            borderRadius: 12,
            alignItems: "center",
        },
    });

    return styles;
};
