import { StyleSheet } from "react-native";
import { Colors, Fonts, Spacing } from "../constants";

export const useExploreScreenStyle = () => {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: Colors.backgroundColors.primary,
        },
        header: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingHorizontal: Spacing.medium,
            paddingVertical: Spacing.large,
            paddingTop: 16,
        },
        headerTitle: {
            fontSize: 28,
            fontFamily: Fonts.heading.family,
            fontWeight: "700",
            color: Colors.text.primary,
        },
        searchButton: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: "#F0F8F0",
            justifyContent: "center",
            alignItems: "center",
        },
        contentContainer: {
            paddingBottom: 32,
        },
        section: {
            marginBottom: 32,
            paddingHorizontal: 16,
        },
        sectionHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 16,
        },
        sectionTitle: {
            fontSize: 20,
            fontFamily: Fonts.heading.family,
            fontWeight: "600",
            color: Colors.text.primary,
            marginBottom: 16,
        },
        seeAllText: {
            fontSize: 16,
            fontFamily: Fonts.body.family,
            fontWeight: "500",
            color: "#4DA1A9",
        },
        // Currency Converter Styles
        currencyConverterCard: {
            backgroundColor: Colors.backgroundColors.primary,
            borderRadius: 16,
            padding: 20,
            elevation: 3,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            borderWidth: 1,
            borderColor: "#4DA1A915",
        },
        currencyHeader: {
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 12,
        },
        currencyIconContainer: {
            width: 50,
            height: 50,
            borderRadius: 25,
            backgroundColor: "#4DA1A915",
            justifyContent: "center",
            alignItems: "center",
            marginRight: 16,
        },
        currencyInfo: {
            flex: 1,
        },
        currencyTitle: {
            fontSize: 18,
            fontFamily: Fonts.heading.family,
            fontWeight: "600",
            color: Colors.text.primary,
            marginBottom: 4,
        },
        currencySubtitle: {
            fontSize: 14,
            fontFamily: Fonts.body.family,
            color: Colors.text.secondary,
            lineHeight: 20,
        },
        currencyExample: {
            backgroundColor: "#F8F9FA",
            borderRadius: 8,
            padding: 12,
            marginTop: 8,
        },
        currencyExampleText: {
            fontSize: 14,
            fontFamily: Fonts.body.family,
            color: "#4DA1A9",
            fontWeight: "500",
            textAlign: "center",
        },
        // Weather Styles
        weatherContainer: {
            paddingRight: 16,
        },
        weatherCard: {
            backgroundColor: Colors.backgroundColors.primary,
            borderRadius: 12,
            padding: 16,
            marginRight: 12,
            width: 140,
            elevation: 2,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
        },
        weatherHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 8,
        },
        weatherCity: {
            fontSize: 14,
            fontFamily: Fonts.heading.family,
            fontWeight: "600",
            color: Colors.text.primary,
        },
        weatherTemp: {
            fontSize: 24,
            fontFamily: Fonts.heading.family,
            fontWeight: "700",
            color: "#4DA1A9",
            marginBottom: 4,
        },
        weatherDesc: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            color: "#637887",
        },
        // Destinations Styles
        destinationsContainer: {
            paddingRight: 16,
        },
        destinationCard: {
            backgroundColor: Colors.backgroundColors.primary,
            borderRadius: 12,
            marginRight: 16,
            width: 240,
            elevation: 2,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            overflow: "hidden",
        },
        destinationImage: {
            width: "100%",
            height: 140,
        },
        destinationContent: {
            padding: 12,
        },
        destinationHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 4,
        },
        destinationName: {
            fontSize: 16,
            fontFamily: Fonts.heading.family,
            fontWeight: "600",
            color: Colors.text.primary,
            flex: 1,
        },
        trendingBadge: {
            backgroundColor: "#FF6B6B",
            borderRadius: 8,
            paddingHorizontal: 6,
            paddingVertical: 2,
        },
        trendingText: {
            fontSize: 10,
            fontFamily: Fonts.body.family,
            fontWeight: "600",
            color: "#FFFFFF",
        },
        destinationCountry: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            color: "#637887",
            marginBottom: 6,
        },
        destinationDesc: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            color: "#637887",
            lineHeight: 16,
            marginBottom: 8,
        },
        destinationFooter: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        destinationPrice: {
            fontSize: 14,
            fontFamily: Fonts.heading.family,
            fontWeight: "600",
            color: "#4DA1A9",
        },
        destinationTime: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            color: "#637887",
        },
        // Real Weather Styles
        realWeatherCard: {
            backgroundColor: Colors.backgroundColors.primary,
            borderRadius: 12,
            padding: 16,
            marginRight: 12,
            width: 160,
            elevation: 2,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
        },
        realWeatherHeader: {
            marginBottom: 8,
        },
        realWeatherCity: {
            fontSize: 16,
            fontFamily: Fonts.heading.family,
            fontWeight: "600",
            color: Colors.text.primary,
        },
        realWeatherCountry: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            color: "#637887",
        },
        realWeatherMain: {
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 8,
        },
        realWeatherIcon: {
            fontSize: 32,
            marginRight: 8,
        },
        realWeatherTemp: {
            fontSize: 24,
            fontFamily: Fonts.heading.family,
            fontWeight: "700",
            color: "#4DA1A9",
        },
        realWeatherCondition: {
            fontSize: 14,
            fontFamily: Fonts.body.family,
            color: Colors.text.primary,
            marginBottom: 8,
        },
        realWeatherDetails: {
            flexDirection: "row",
            justifyContent: "space-between",
        },
        realWeatherDetail: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            color: "#637887",
        },
        // Popular Destinations Styles
        popularDestCard: {
            backgroundColor: Colors.backgroundColors.primary,
            borderRadius: 12,
            padding: 16,
            marginRight: 12,
            width: 280,
            elevation: 2,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
        },
        destHeader: {
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 12,
        },
        countryFlag: {
            width: 32,
            height: 24,
            borderRadius: 4,
            marginRight: 12,
        },
        destInfo: {
            flex: 1,
        },
        destCountry: {
            fontSize: 16,
            fontFamily: Fonts.heading.family,
            fontWeight: "600",
            color: Colors.text.primary,
        },
        destCapital: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            color: "#637887",
        },
        budgetBadge: {
            backgroundColor: "#7ED95715",
            borderRadius: 12,
            paddingHorizontal: 8,
            paddingVertical: 4,
        },
        budgetText: {
            fontSize: 10,
            fontFamily: Fonts.body.family,
            fontWeight: "600",
            color: "#7ED957",
        },
        destDescription: {
            fontSize: 14,
            fontFamily: Fonts.body.family,
            color: "#637887",
            lineHeight: 20,
            marginBottom: 12,
        },
        destDetails: {
            flexDirection: "row",
            flexWrap: "wrap",
            marginBottom: 12,
        },
        destDetail: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            color: "#637887",
            marginRight: 12,
            marginBottom: 4,
        },
        attractionsContainer: {
            marginTop: 8,
        },
        attractionsTitle: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            fontWeight: "600",
            color: Colors.text.primary,
            marginBottom: 4,
        },
        attractionsList: {
            marginLeft: 8,
        },
        attractionItem: {
            fontSize: 11,
            fontFamily: Fonts.body.family,
            color: "#637887",
            lineHeight: 16,
        },
        // Places Styles
        placeCategoryTitle: {
            fontSize: 16,
            fontFamily: Fonts.heading.family,
            fontWeight: "600",
            color: Colors.text.primary,
            marginBottom: 12,
            paddingHorizontal: 16,
        },
        placesContainer: {
            paddingRight: 16,
        },
        placeCard: {
            backgroundColor: Colors.backgroundColors.primary,
            borderRadius: 12,
            padding: 12,
            marginRight: 12,
            width: 200,
            elevation: 2,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
        },
        placeHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "flex-start",
            marginBottom: 8,
        },
        placeName: {
            fontSize: 14,
            fontFamily: Fonts.heading.family,
            fontWeight: "600",
            color: Colors.text.primary,
            flex: 1,
            marginRight: 8,
        },
        ratingContainer: {
            flexDirection: "row",
            alignItems: "center",
        },
        ratingStar: {
            fontSize: 12,
            marginRight: 2,
        },
        ratingText: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            fontWeight: "600",
            color: "#FF9500",
        },
        placeCategory: {
            fontSize: 12,
            fontFamily: Fonts.body.family,
            color: "#4DA1A9",
            marginBottom: 4,
        },
        placeAddress: {
            fontSize: 11,
            fontFamily: Fonts.body.family,
            color: "#637887",
            lineHeight: 16,
            marginBottom: 8,
        },
        placeDistance: {
            fontSize: 11,
            fontFamily: Fonts.body.family,
            color: "#637887",
            marginBottom: 8,
        },
        placeFacilities: {
            flexDirection: "row",
            flexWrap: "wrap",
        },
        facility: {
            fontSize: 10,
            fontFamily: Fonts.body.family,
            color: "#637887",
            marginRight: 8,
            marginBottom: 2,
        },
    });
};
