import { Dimensions, Platform, StyleSheet } from "react-native";
import { Colors } from "../constants/Colors";
import { Fonts } from "../constants/Fonts";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#F9FAFB",
    },
    header: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: "#FFFFFF",
        borderBottomWidth: 1,
        borderBottomColor: "#E5E7EB",
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.1,
                shadowRadius: 4,
            },
            android: {
                elevation: 4,
            },
        }),
    },
    headerTitleContainer: {
        alignItems: "center",
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: "700",
        color: "#1F2937",
        fontFamily: Fonts.heading.family,
        marginBottom: 4,
    },
    headerSubtitle: {
        fontSize: 15,
        color: "#6B7280",
        fontFamily: Fonts.body.family,
        opacity: 0.8,
    },
    searchContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: "#FFFFFF",
        borderBottomWidth: 1,
        borderBottomColor: "#E5E7EB",
    },
    searchBar: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F3F4F6",
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: "#E5E7EB",
    },
    searchInput: {
        flex: 1,
        marginLeft: 12,
        fontSize: 16,
        color: "#1F2937",
        fontFamily: Fonts.body.family,
    },
    noteCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        marginVertical: 8,
        marginHorizontal: 16,
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.1,
                shadowRadius: 8,
            },
            android: {
                elevation: 3,
            },
        }),
        borderWidth: 1,
        borderColor: "#F3F4F6",
    },
    noteHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#F3F4F6",
    },
    authorInfo: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    authorAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 12,
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: 1 },
                shadowOpacity: 0.1,
                shadowRadius: 2,
            },
            android: {
                elevation: 2,
            },
        }),
    },
    authorInitials: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "600",
        fontFamily: Fonts.body.family,
    },
    authorDetails: {
        flex: 1,
    },
    authorName: {
        fontSize: 16,
        fontWeight: "600",
        color: "#1F2937",
        fontFamily: Fonts.body.family,
    },
    noteDate: {
        fontSize: 13,
        color: "#9CA3AF",
        marginTop: 2,
        fontFamily: Fonts.body.family,
    },
    noteActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    importantBadge: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: "#FEF3C7",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#FCD34D",
    },
    importantStar: {
        fontSize: 14,
        color: "#F59E0B",
    },
    actionButtons: {
        flexDirection: "row",
        gap: 8,
    },
    editButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: "#EBF5FF",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#BFDBFE",
    },
    deleteButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: "#FEE2E2",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#FECACA",
    },
    editIcon: {
        fontSize: 16,
        color: "#3B82F6",
    },
    deleteIcon: {
        fontSize: 16,
        color: "#EF4444",
    },
    noteContentContainer: {
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    noteContent: {
        fontSize: 16,
        lineHeight: 24,
        color: "#374151",
        fontFamily: Fonts.body.family,
    },
    emptyState: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 32,
        backgroundColor: "#FFFFFF",
    },
    emptyEmoji: {
        fontSize: 64,
        marginBottom: 24,
    },
    emptyTitle: {
        fontSize: 24,
        fontWeight: "700",
        color: "#1F2937",
        marginBottom: 8,
        textAlign: "center",
        fontFamily: Fonts.heading.family,
    },
    emptySubtitle: {
        fontSize: 17,
        color: "#4B5563",
        marginBottom: 6,
        textAlign: "center",
        fontFamily: Fonts.body.family,
    },
    emptyDescription: {
        fontSize: 15,
        color: "#6B7280",
        textAlign: "center",
        marginBottom: 32,
        fontFamily: Fonts.body.family,
        lineHeight: 22,
    },
    emptyButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#10B981",
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: 12,
        gap: 10,
        ...Platform.select({
            ios: {
                shadowColor: "#10B981",
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.3,
                shadowRadius: 8,
            },
            android: {
                elevation: 8,
            },
        }),
    },
    emptyButtonText: {
        color: "#FFFFFF",
        fontSize: 17,
        fontWeight: "600",
        fontFamily: Fonts.body.family,
    },
    floatingAddButton: {
        position: "absolute",
        bottom: 30,
        right: 20,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: Colors.primary,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        paddingHorizontal: 16,
    },
    modalContainer: {
        backgroundColor: "#FFFFFF",
        borderRadius: 20,
        padding: 20,
        width: width - 32,
        maxHeight: Platform.OS === "ios" ? "80%" : "90%",
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.25,
                shadowRadius: 12,
            },
            android: {
                elevation: 8,
            },
        }),
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#E5E7EB",
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: "700",
        color: "#1F2937",
        fontFamily: Fonts.heading.family,
    },
    modalContent: {
        marginBottom: 20,
    },
    noteInput: {
        minHeight: 120,
        maxHeight: 200,
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        color: "#1F2937",
        marginBottom: 16,
        fontFamily: Fonts.body.family,
        borderWidth: 1,
        borderColor: "#E5E7EB",
    },
    importantToggle: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F9FAFB",
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E5E7EB",
    },
    importantText: {
        fontSize: 15,
        color: "#6B7280",
        marginLeft: 10,
        fontFamily: Fonts.body.family,
    },
    importantTextActive: {
        color: "#F59E0B",
    },
    modalActions: {
        flexDirection: "row",
        justifyContent: "flex-end",
        gap: 12,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: "#E5E7EB",
    },
    cancelButton: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 10,
        backgroundColor: "#F3F4F6",
        borderWidth: 1,
        borderColor: "#E5E7EB",
    },
    cancelButtonText: {
        fontSize: 15,
        color: "#4B5563",
        fontWeight: "600",
        fontFamily: Fonts.body.family,
    },
    saveButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 10,
        backgroundColor: "#10B981",
        ...Platform.select({
            ios: {
                shadowColor: "#10B981",
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.2,
                shadowRadius: 4,
            },
            android: {
                elevation: 4,
            },
        }),
    },
    saveButtonDisabled: {
        backgroundColor: "#9CA3AF",
    },
    saveButtonText: {
        fontSize: 15,
        color: "#FFFFFF",
        fontWeight: "600",
        fontFamily: Fonts.body.family,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        color: "#6B7280",
        fontFamily: Fonts.body.family,
    },
    errorContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 32,
        backgroundColor: "#FFFFFF",
    },
    errorEmoji: {
        fontSize: 64,
        marginBottom: 24,
    },
    errorTitle: {
        fontSize: 24,
        fontWeight: "700",
        color: "#1F2937",
        marginBottom: 8,
        textAlign: "center",
        fontFamily: Fonts.heading.family,
    },
    errorText: {
        fontSize: 16,
        color: "#4B5563",
        textAlign: "center",
        marginBottom: 32,
        fontFamily: Fonts.body.family,
        lineHeight: 24,
    },
    retryButton: {
        backgroundColor: "#10B981",
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: 12,
        ...Platform.select({
            ios: {
                shadowColor: "#10B981",
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.3,
                shadowRadius: 8,
            },
            android: {
                elevation: 8,
            },
        }),
    },
    retryButtonText: {
        color: "#FFFFFF",
        fontSize: 17,
        fontWeight: "600",
        fontFamily: Fonts.body.family,
    },
});
